var strVar="";
strVar += "<div class=\"header_sec\"><div class=\"headercontent\"><div class=\"logo\"><img src=\"images\/schoollogo.jpg\" alt=\"\" class=\"schoollogo\">";
strVar += "					<\/div>";
strVar += "					<div class='right-title'>长沙理工大学计通学院赴湖南省少数民族区域网络安全“护卫队”志愿服务实践项目<\/div>";
strVar += "				<\/div>";
strVar += "			<\/div>";
strVar += "";
strVar += "			<div class=\"placelink\">";
strVar += "				<ul>";
strVar += "					<li id=\"shijiandidian\">";
strVar += "						<a href=\"news.html\">实践地点<\/a>";
strVar += "						<ul class=\"drop_down\">";
strVar += "							<a href=\".\/news1.html\">";
strVar += "								<li>怀化<\/li>";
strVar += "							<\/a>";
strVar += "							<a href=\".\/news3.html\">";
strVar += "								<li>吉首<\/li>";
strVar += "							<\/a>";
strVar += "							<a href=\".\/news5.html\">";
strVar += "								<li>张家界<\/li>";
strVar += "							<\/a>";
strVar += "						<\/ul>";
strVar += "					<\/li>";
strVar += "					<li id=\"shijianzhuti\">";
strVar += "						<a href=\"\">实践主题<\/a>";
strVar += "						<ul class=\"drop_down\">";
strVar += "							<a href=\"https:\/\/mp.weixin.qq.com\/s\/sRxHo-1h_ETDYrl9kMM8MA\"  target='_blank'>";
strVar += "								<li>网络安全知识<\/li>";
strVar += "							<\/a>";
strVar += "							<a href=\"https:\/\/mp.weixin.qq.com\/s\/3NILjBuehQOWF3E7v517ZA\"  target='_blank'>";
strVar += "								<li>相关案例介绍<\/li>";
strVar += "							<\/a>";
strVar += "						<\/ul>";
strVar += "					<\/li>";
strVar += "					<li id=\"shijianzhoubao\">";
strVar += "						<a href=\"shijianzhoubao.html\">实践周报<\/a>";
strVar += "					<\/li>";
strVar += "					<li id=\"shijianriji\">";
strVar += "						<a href=\"shijianriji.html\">实践日记<\/a>";
strVar += "					<\/li>";
strVar += "					<li id=\"xccg\">";
strVar += "						<a href=\"news9.html\">宣传成果<\/a>";
strVar += "					<\/li>";
strVar += "					<li id=\"diaoyanbaogao\">";
strVar += "						<a href=\"diaoyanbaogao.html\">调研报告<\/a>";
strVar += "					<\/li>";
strVar += "				<\/ul>";
strVar += "			<\/div>";
$(".header").html(strVar);





strVar="";
strVar += "			<div class=\"footer-b\">";
strVar += "				<div class=\"foot-nav\">";
strVar += "					<a href=\"https:\/\/www.universitychina.net\/shijian\/diaoyan\/20230709\/131239.html\" target='_blank'>";
strVar += "						中国大学生网";
strVar += "					<\/a>";
strVar += "";
strVar += "					<a href=\"https:\/\/www.universitychina.net\/shijian\/diaoyan\/20230711\/132002.html\" target='_blank'>大学生网<\/a>";
strVar += "					<a href=\"https:\/\/www.coluniv.com\/shijian\/43147.html\" target='_blank'>多彩大学生网<\/a>";
strVar += "				<\/div>";
strVar += "				<div class=\"copyright fcc-h\">";
strVar += "					<p>";
strVar += "						湖南省长沙市天心区万家丽南路2段960号";
strVar += "					<\/p>";
strVar += "					<p>";
strVar += "						邮编: 410114";
strVar += "					<\/p>";
strVar += "					<p>";
strVar += "						长沙理工大学计通学院版权所有 Copyright © 2023";
strVar += "					<\/p>";
strVar += "				<\/div>";
strVar += "			<\/div>";
$(".footer").html(strVar);